name: My first Github Workflow
on: [push]
jobs:	
    Sprawdzenie_wersji:
       runs-on: ubuntu-latest
       steps:
         - name: wersja pythona
           run: 
             python3 --version
         - name: wersja dockera
           run:
             docker --version 
    Testowanie_kodu:
       runs-on: ubuntu-latest
       steps:
         - name: pylint
           run:
             python -m pip install --upgrade pip
             pip install pylint
             pip install -r requirements.txt
             pylint app.py
    Budowanie_obrazu_aplikacji:
       runs-on: ubuntu-latest
       steps:
         - name: docker
           run:
             docker build --tag test-flask-app .
