name: My first Github Workflow
on: [push]
jobs:	
    Version_check:
       runs-on: ubuntu-latest
       steps:
         - name: python version
           run: 
             python3 --version
         - name: docker version
           run:
             docker --version 
    Testing_codeu:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: setup
           uses: actions/setup-python@v1
           with:
             python-version: 3.8
         - name: Install pylint
           run:
             python -m pip install --upgrade pip
             pip install pylint
             pip install -r requirements.txt
         - name: pylint
           run:
             pylint --exit-zero app.py
    Budowanie_obrazu_aplikacji:
       runs-on: ubuntu-latest
       steps:
         -name: docker group
         - run: 
             sudo groupadd docker
             sudo usermod -aG docker $USER
             newgrp - docker
         - uses: actions/checkout@v2
         - name: docker
           run:
             sudo snap install docker
             sudo docker build -t test-flask-app .
