name: My first Github Workflow
on: [push]
jobs:	
    Sprawdzenie wersji:
       runs-on: ubuntu-latest
       steps:
         - name: wersja pythona
           run: 
             python3 --version
         - name: wersja dockera
           run:
             docker --version 
    Testowanie kodu:
       runs-on: ubuntu-latest
       steps:
         - name: pylint
           run:
             python -m pip install --upgrade pip
             pip install pylint
             if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
             pylint app.py
    Budowanie obrazu aplikacji:
       runs-on: ubuntu-latest
       steps:
         - name: docker
           run:
             docker build --tag test-flask-app .
