name: My first Github Workflow
on: [push]
jobs:	
    Version_check:
       runs-on: ubuntu-latest
       steps:
         - name: python version
           run: 
             python3 --version
         - name: docker version
           run:
             docker --version 
    Code_testing:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: setup
           uses: actions/setup-python@v1
           with:
             python-version: 3.8
         - name: Install pylint
           run:
             python -m pip install --upgrade pip
             pip install pylint
             pip install -r requirements.txt
         - name: pylint
           run:
             pylint --exit-zero app.py
    Docker:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v1
         - name: docker build
           run:
             docker image build -t test-flask-app .
