name: My first Github Workflow
on: [push]
jobs:	
    Sprawdzenie_wersji:
       runs-on: ubuntu-latest
       steps:
         - name: wersja pythona
           run: 
             python3 --version
         - name: wersja dockera
           run:
             docker --version 
    Testowanie_kodu:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: setup
           uses: actions/setup-python@v1
           with:
             python-version: 3.8
         - name: Install
           run:
             python -m pip install --upgrade pip
             pip install pylint
             pip install -r requirements.txt
         - name: pylint
           run:
             pylint app.py
    Budowanie_obrazu_aplikacji:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: docker
           run:
             sudo snap install docker
             sudo docker build -t test-flask-app .
