name: My first Github Workflow
on: [push]
jobs:	
    Sprawdzenie_wersji:
       runs-on: ubuntu-latest
       steps:
         - name: wersja pythona
           run: 
             python3 --version
         - name: wersja dockera
           run:
             docker --version 
    Testowanie_kodu:
       runs-on: ubuntu-latest
       steps:
         - name: pylint install
           run:
             pip3 install -r requirements.txt
         - name: pylint
           run:
             pylint --rcfile=.pylintrc app.py
    Budowanie_obrazu_aplikacji:
       runs-on: ubuntu-latest
       steps:
         - name: docker
           run:
             docker build --tag test-flask-app .
